repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
        - id: isort
          name: isort
          stages: [commit]

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
        - id: black
          name: black
          stages: [commit]
          language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: flake8
        exclude: ^tests/
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.1.1
    hooks:
    -   id: pylint
        exclude: ^tests/

-   repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [commit]
      entry: pytest --tb=line -n 4 --deselect=setup.py tests/
      language: system
      types: [python]

    - id: pytest-cov
      name: pytest-cov
      stages: [commit]
      language: system
      entry: pytest --cov=marmot --tb=no --ignore=*setup.py --cov-fail-under=80 -n 4
      types: [python]
      pass_filenames: false
